### ISSUE TITLE
Environment Variable Naming Overlap

### ISSUE THREAD

**Issue by montasaurus** [sarsena/incontact_api#5]
Thanks for providing this gem. It's been helpful for me to get going with the InContact API.

I'm working on a project to incorporate the API, but ran into an issue with the ENV variable naming. In the project, I'm saving multiple username/password combinations as ENV variables. The keys this gem uses (`USERNAME` and `PASSWORD`) weren't easy for me to identify as belonging to the InContact API. To solve this, I prefixed the keys with `IC_`, similar to how AWS handles ENV variables in their gem.

I realize implementing this would be a breaking change for you. To be able to use these prefixes internally, I created a [fork](https://github.com/BlackcombSoftware/incontact). I started adding some more functionality and documentation from how I was using it, and renamed the gem so I wouldn't have to remember how underscores work in gem naming. I haven't modified the authors section of the gemspec, and don't plan to publish the modifications outside of the repo. I'd be happy to create pull requests for anything in the fork that you find useful, or just keep using the modifications internally.

Thanks again,
Adam

**Comment by sarsena** [comment]
Hey @howitzer-industries so the only reason I set the env to be username was in the InContact docs they mentioned passing in `username`, `password`, `grant_type`, etc.  I just decided to make the ENV vars the same name as the keys.  
You can see that here.
https://github.com/sarsena/incontact_api/blob/master/lib/incontact_api.rb#L52-L60

I wouldn't mind changing them to prefix `IC_` thats probably a good idea given the fact anyone using this app could use `username` or `password` as other env vars.  If you want to open a PR I would be happy to review it.
